"""Build helper: write version_info.txt from launcher/__init__.py.

PyInstaller stamps this into the exe as a Windows VERSIONINFO resource, so
the shipped file answers "which version is this?" without launching it:
right-click TAOS_Launcher.exe -> Properties -> Details -> File version.

Run automatically by build.bat. Generated file is disposable.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
INIT = ROOT / "launcher" / "__init__.py"
DST = ROOT / "version_info.txt"

TEMPLATE = """# Auto-generated by make_version_info.py - do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=%(tup)s,
    prodvers=%(tup)s,
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(u'040904B0', [
        StringStruct(u'CompanyName', u'THU Tribe Studios - The Alchemy of a Storm'),
        StringStruct(u'FileDescription', u'TAOS Launcher'),
        StringStruct(u'FileVersion', u'%(ver)s'),
        StringStruct(u'InternalName', u'TAOS_Launcher'),
        StringStruct(u'LegalCopyright', u'The Alchemy of a Storm'),
        StringStruct(u'OriginalFilename', u'TAOS_Launcher.exe'),
        StringStruct(u'ProductName', u'TAOS Launcher'),
        StringStruct(u'ProductVersion', u'%(ver)s')])
    ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""

m = re.search(r'__version__\s*=\s*"([^"]+)"', INIT.read_text(encoding="utf-8"))
if not m:
    raise SystemExit("ERROR: no __version__ found in %s" % INIT)
ver = m.group(1)

parts = [int(p) for p in ver.split(".")]
while len(parts) < 4:
    parts.append(0)
tup = tuple(parts[:4])

DST.write_text(TEMPLATE % {"tup": tup, "ver": ver}, encoding="utf-8")
print("version_info.txt <- v%s %s" % (ver, tup))
